version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  chatapp:
    build: 
      context: .
      dockerfile: Dockerfile

    command: >
      sh -c "python chatapp/manage.py migrate &&
             python chatapp/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/chatapp/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      #- huggingface_model
    environment:
      - REDIS_URL=redis://redis:6379

  channels:
    build: 
      context: .
    command: >
      sh -c "python chatapp/manage.py migrate &&
             daphne -b 0.0.0.0 -p 8001 chatapp.asgi:application"

    volumes:
      - .:/chatapp/
    ports:
      - "8001:8001"
    depends_on:
      - redis
      #- huggingface_model

    environment:
      - REDIS_URL=redis://redis:6379

  #huggingface_model:
    #image: huggingface/transformers-pytorch-gpu
    #ports:
      #- "8501:8501"
    #volumes:
      #- ./huggingface-model:/models
    #command: >
      #sh -c "python -m transformers.cli serving \
      #--model-id 5CD-AI/Vietnamese-Sentiment-visobert \
      #-- task text-classification \
      #-- device cuda"

